In [1]:
import numpy as np

In [4]:
a = np.array([10.0, 100.0, 100.0, 1.0, 10.0, 100.0, 10.0 ])
b = np.array([1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0])
c = np.array([0, 0, 0, 0, 0, 0, 0])

In [10]:
np.where(a > 20.0)

(array([1, 2, 5], dtype=int64),)

In [12]:
np.where(b == 0.0)

(array([1, 3, 5], dtype=int64),)

In [14]:
indices = np.intersect1d(np.where(a > 20.0), np.where(b == 0.0))

In [19]:
groups = np.split(a, indices)
print(groups)

[array([10.]), array([100., 100.,   1.,  10.]), array([100.,  10.])]


In [18]:
[np.delete(a, 0) for a in groups[1:]]

[array([100.,   1.,  10.]), array([10.])]

In [21]:
[groups[0]] + [np.delete(a, 0) for a in groups[1:]]

[array([10.]), array([100.,   1.,  10.]), array([10.])]

In [23]:
d = np.array([1, 0, 1, 0, 1])
d[0::2]

array([1, 1, 1])